- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t jpetstore .
      args:
        chdir: /var/lib/jenkins/workspace/jpetstore

    - name: tag image
      command: docker tag jpetstore:latest raji0808/jpetstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: raji0808
        password: dckr_pat_sRBBG8v4nNCH9u61gIO06whZbvM

    - name: Push image
      command: docker push raji0808/jpetstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 raji0808/jpetstore:latest
